name: Generate Snake Animation

on:
  schedule:
    # Every 6 hours
   # - cron: "0 */6 * * *"
   # Every 5 minutes
    - cron: "*/5 * * * *"

  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: snake-animation
  cancel-in-progress: true

jobs:
  generate:
    name: Generate Contribution Snake
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: p1oto
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
